var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)?!0:!1;var isPhone=/Android|webOS|iPhone|BlackBerry/i.test(navigator.userAgent)?!0:!1;var controller=new ScrollMagic.Controller();var posterImg='.video-container .poster img';var page=$('body > .container-fluid').attr('id');function prepImages(){var smallImages=$('img[src*="_bg.png"]')||[];if(!$(smallImages).hasClass('no-resize')&&(page=='home'||page=='service'||page=='contact')){$(smallImages).each(function(){var oldImg=this;var src=($(this).attr('src')).split('.')[0]+'_2x.png';var imageDiv=$('<img src="'+src+'" style="'+$(oldImg).attr('style')+'" alt="retina hero image" />');$(imageDiv).load(function(){$(oldImg).attr('src',src);imageDiv=null})})}
if(page=='home'||page==''){var otherImgs=['data','service','capabilities1','capabilities2'];$(otherImgs).each(function(){var src=this;var imageDiv=$('<img src="img/block_'+src+'.png" />');$(imageDiv).load(function(){imageDiv=null})})}}
function prepAnimations(){var animationContainer=$('<div id="animation_container" class="hidden-xs-down" style="position: absolute; top: 0; left: 0; z-index: 3;"><canvas id="animation_canvas" style="position: absolute; display: block; opacity: 0;"></canvas><div id="dom_overlay_container" style="pointer-events:none; overflow:hidden; position: absolute; left: 0px; top: 0px; display: block;"></div></div>');if($('.hero-animation').length){var aniCookie=document.cookie.split(page+'-animation-loaded=')[1];if(aniCookie==undefined){document.cookie=page+'-animation-loaded=true';$('.'+page+'-page').append(animationContainer)}
init()}}
function scrollNav(){var scrollTopStart=0,scrollTopZero=0;$('nav a').focus(function(){$('nav').removeClass('slideOut')});$(window).scroll(function(){if((scrollTopZero<1)){scrollTopZero+=1}else if((scrollTopZero!==0)&&($(window).scrollTop()>75)||(scrollTopStart>75)){var scrollTopEnd=$(window).scrollTop();var scrollSpeed=(scrollTopEnd-scrollTopStart);if((scrollTopEnd>=(scrollTopStart+15))&&(scrollTopStart>75)&&(!$('nav .navbar-collapse').hasClass('in'))){$('nav').addClass('slideOut')}else if(((scrollTopEnd+15)<=scrollTopStart)){$('nav').removeClass('slideOut')}
scrollTopStart=scrollTopEnd}else{$('nav').removeClass('slideOut')}})}
function scrollAnimate(){var squiggle=$("path#squiggle");squiggle.css('opacity',1);function pathPrepare(element){var lineLength=element[0].getTotalLength();element.css("stroke-dasharray",lineLength);element.css("stroke-dashoffset",lineLength)}
pathPrepare(squiggle);var squiggleAnimation=new TimelineMax().add(TweenLite.to(squiggle,1,{strokeDashoffset:0,ease:Linear.easeNone}));var squiggleScene=new ScrollMagic.Scene({triggerElement:".animation-trigger",duration:$('.animation-trigger').height()}).setTween(squiggleAnimation).addTo(controller);if($('.dot').length){$('.dot').each(function(){var dir=function(){if($(window).width()>992){return 'left'}else{return 'top'}},cssStart={opacity:0},cssEnd={opacity:1};cssStart[dir()]='-30px';cssEnd[dir()]='0px';var line=$('.line',this),pin=$('.pin',this),text=$('.text',this),arrow=$('.down-arrow',this),height=this.clientHeight;var pinAnimation=new TimelineMax().to(line,0.5,{width:'80%',right:0}).fromTo(pin,0.5,{width:'0px',height:'0px'},{width:'25px',height:'25px'},'-=0.5').fromTo(text,1,{css:cssStart},{css:cssEnd},'-=0.5').from(arrow,0.5,{opacity:0,top:'-15px'},'-=0.5');var pinAnimationScene=new ScrollMagic.Scene({triggerElement:this,reverse:!1,tweenChanges:!0}).setTween(pinAnimation).addTo(controller);var classAddScene=new ScrollMagic.Scene({triggerElement:this,duration:height}).setClassToggle(this,'inview').addTo(controller)})}}
function parallax(el){var containerHeight=$(el).parent().height(),elHeight=$(el).height(),imgType=$(el).css('background-image').split(/["/]/),fileName=imgType[imgType.length-2].split(/[_.]/)[1],img=$('<img src="img/'+page+'_'+fileName+'_parallax.png">');$(img).load(function(){$(el).css('background-image','url("img/'+page+'_'+fileName+'_parallax.png"').addClass('parallax');var scene=new ScrollMagic.Scene({triggerElement:el,triggerHook:'center',duration:$(window).width()+'px',ease:Linear.easeOut}).setTween(TweenLite.fromTo(el,1,{'background-position-y':'0%'},{'background-position-y':'80%'})).addTo(controller);img=null})}
function playVideo(){$('.playBtn, .playBtn + .video').click(function(){if(!$('.videoPlayer').length){var overlay='',videoHeight=function(){$('div[id*="kaltura_player"]').height(($('div[id*="kaltura_player"]').width())/1.78)},video='<div class="video-overlay row no-gutters align-items-center justify-content-center w-100 h-100"><div id="homepageVideo" class="col-12 col-md-10" itemprop="video" itemscope itemtype="http://schema.org/VideoObject"><span itemprop="duration" content="167"></span></div><script src="'+$('.playBtn + .video img',$(this).parent()).attr('data-video')+'&width=500&height=300&flashvars[streamerType]=auto&flashvars[autoPlay]=true&flashvars[playPauseBtn.plugin]=false&flashvars[largePlayBtn.plugin]=false&flashvars[loadingSpinner.plugin]=false&flashvars[topBarContainer.plugin]=false&flashvars[fullScreenBtn.plugin]=false&flashvars[logo.plugin]=false&flashvars[sourceSelector.plugin]=false"></script></div>';$('body').prepend(video);videoHeight();$('.video-overlay').animate({opacity:'1'},100);$(window).on('resize',function(){videoHeight()})}});$('body').on('click','.video-overlay',function(){$(this).animate({opacity:'0'},100,function(){kWidget.destroy('homepageVideo');$(this).remove()})})}
function mainMenuAnimation(){$('.homepage_menu .container > div').click(function(){var arrow=$('<div class="arrow row no-gutters"><div class="arrow-1 col-6 p-0"></div><div class="arrow-2 col-6 p-0"></div></div>');var fadeBox=$('<section class="fadeBox" style="position: absolute; height: 100%; width: 100%; z-index: 10; display: none;"></section>');var category=this.className.split('cat-')[1];if(!($(this).hasClass('selected'))){$('.two-block .container > div:not(.hidden-md-up) > div, #'+category+' > div').prepend(fadeBox);$('.left .fadeBox').addClass('blue-bg');$('.right .fadeBox').addClass('white-bg');$('.fadeBox').fadeIn('fast',function(){$('.two-block .container > div:not(.hidden-md-up)').addClass('hidden-md-up');$('.two-block .container #'+category).removeClass('hidden-md-up')}).delay(100).fadeOut('fast',function(){$(this).remove();if(category=='data'||category=='service'||category=='capabilities'){$('#'+category).addClass('animated')}});$('.selected .arrow').parent().empty();$('.selected').removeClass('selected');$(this).addClass('selected');$('.cat-'+category+' > div:last-child').html(arrow)}});if($('.two-block .graph').length){var graph=$('.two-block .graph'),graphEl=$('<div class="h-100"><div class="graphblock w-100 h-100" style="position: absolute;"><div class="circle1" style="top: 66%; left: -97%;"></div></div> \
            <div class="line" style="transform: rotate(34deg); -webkit-transform: rotate(34deg); -moz-transform: rotate(34deg); left: -40%; top: 44%;"></div> \
            <div class="graphblock w-100 h-100" style="position: absolute;"><div class="circle2" style="top: 40%; left: -25%;"></div></div> \
            <div class="line" style="transform: rotate(-52deg); -webkit-transform: rotate(-52deg); -moz-transform: rotate(-52deg); left: 37%; top: 10%; "></div> \
            <div class="graphblock w-100 h-100" style="position: absolute;"><div class="circle3" style="top: 52%; left: 55%;"></div></div> \
            <div class="line" style="transform: rotate(39deg); -webkit-transform: rotate(39deg); -moz-transform: rotate(39deg); top: -29%; left: 110%;"></div> \
            <div class="graphblock w-100 h-100" style="position: absolute;"><div class="circle4" style="top: 25%; left: 138%;"></div></div></div>'),graphController=new ScrollMagic.Controller();$(graph).html(graphEl);var drawGraph=new TimelineMax().from('.circle1',0.5,{scale:0}).from('.circle2',0.5,{scale:0},'-=0.3').from('.circle3',0.5,{scale:0},'-=0.3').from('.circle4',0.5,{scale:0},'-=0.3').from('.line',0.5,{scale:0,opacity:0},'-=0.3'),drawGraphScene=new ScrollMagic.Scene({triggerElement:'#results',offset:50,reverse:!1}).setTween(drawGraph).setClassToggle('#results','animated').addTo(graphController)}}
function dataContainerClick(){$('.datacontainer').css('cursor','pointer').each(function(){$(this).prepend('<div class="plus row no-gutters align-items-center w-100 h-100 font-weight-bold" style="position: absolute; z-index: 5; color: #FFF;"><p class="col" aria-hidden="true">+</p></div>')});$('.datacontainer').on('click',function(){if(!$(this).hasClass('clicked')){$('.plus',this).fadeOut('fast');$(this).addClass('clicked')}else{$('.plus',this).fadeIn('fast');$(this).removeClass('clicked')}})}(function($){$.fn.inview=function(options){var wh=$(window).height()/2,settings=$.extend({delay:wh,removeClass:!0,oneAtATime:!1},options),elems=[];this.each(function(){elems.push(this)});var positionCheck=function(){var scroll=$(window).scrollTop();$.each(elems,function(i,val){var elTop=$(val).offset().top;if((elTop<scroll+settings.delay&&elTop>scroll)){if(settings.oneAtATime!=!1&&$('.inview').length){$('.inview:not(:last)').removeClass('inview')}
$(val).addClass('inview')}else if(settings.removeClass==!0){$(val).removeClass('inview')}})};if(elems.length>0){positionCheck();$(window).scroll(function(){positionCheck()})}}})(jQuery);function loadFont(){var MTUserId='19215901-05b8-4a80-ad4a-d7965b56410d';var MTFontIds=new Array();MTFontIds.push("903286");(function(){var mtTracking=document.createElement('script');mtTracking.type='text/javascript';mtTracking.async='true';mtTracking.src='js/mtiFontTrackingCode.js';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(mtTracking)})()}
function scaleVideoContainer(){$('.poster img').css({'position':'absolute'});var height=$(window).height();var unitHeight=parseInt(height)+'px';$('.homepage-video-module').css('height',unitHeight)}
function initBannerVideoSize(element){$(element).each(function(){$(this).css('width',this.naturalWidth);$(this).css('height',this.naturalHeight)});scaleBannerVideoSize(element)}
function scaleBannerVideoSize(element,fullScreen){var chkFullScrn=function(){if(fullScreen!=!1){return $(window).height()}else{return $('.header').height()}};var windowWidth=$(window).width(),windowHeight=chkFullScrn(),videoWidth,videoHeight;$(element).each(function(){var videoAspectRatio=(this.naturalHeight/this.naturalWidth)||9/16,windowAspectRatio=windowHeight/windowWidth;if(videoAspectRatio>windowAspectRatio){videoWidth=windowWidth;videoHeight=videoWidth*videoAspectRatio;$(this).css({'top':-(videoHeight-windowHeight)/2+'px','margin-left':0})}else{videoHeight=windowHeight;videoWidth=videoHeight/videoAspectRatio;$(this).css({'margin-top':0,'margin-left':-(videoWidth-windowWidth)/2+'px'})}
$(this).width(videoWidth).height(videoHeight)})}
function videoPlaying(playerId,kdp,video,selector){$(selector).delay(1000).fadeTo('slow',0);kdp.kBind('thirdQuartile',function(){$(selector).fadeTo('slow',1,function(){kWidget.destroy(playerId)})});$(window).on('resize',function(){initBannerVideoSize(video);scaleBannerVideoSize(video,!1)})}
function homepageVideoScaler(){kWidget.embed({targetId:'homepageVideo',wid:'_420261',uiconf_id:'30915021',entry_id:'1_cbrqjld2',cache_st:'1499965041',flashvars:{streamerType:'auto',autoPlay:!0,autoMute:!0,stretchVideo:!0,largePlayBtn:{plugin:!1},loadingSpinner:{plugin:!1},topBarContainer:{plugin:!1},controlBarContainer:{plugin:!1},autoRewind:!1,loop:!1}});kWidget.addReadyCallback(function(playerId){var muteBtn=$('<div style="position: absolute; width: 50px; height: 50px; right: 0; top: 3.5%; display: none; cursor: pointer; z-index: 200"><img src="img/muteBtn_on.png" alt="Mute" /></div>');var video=$('.mwPlayerContainer, .videoHolder, .mwEmbedPlayer',frames.homepageVideo_ifp.document);var kdp=document.getElementById(playerId);initBannerVideoSize(video);scaleBannerVideoSize(video);$('.homepage-video-module').prepend($(muteBtn).fadeIn('slow'));kdp.kBind('playerPlayed',videoPlaying(playerId,kdp,video,'.poster img'));$(muteBtn).click(function(){var volume=kdp.evaluate('{video.volume}');if(volume>0){kdp.sendNotification('changeVolume',0);$('img',muteBtn).attr('src','img/muteBtn_on.png')}else{kdp.sendNotification('changeVolume',1);$('img',muteBtn).attr('src','img/muteBtn_off.png')}})})}
function heroVideos(){kWidget.addReadyCallback(function(playerId){var video=$('.mwPlayerContainer, .videoHolder, .mwEmbedPlayer',frames[playerId+'_ifp'].document);var kdp=document.getElementById(playerId);scaleBannerVideoSize(video,!1);kdp.kBind('playerStateChange',function(state){if(state=='playing'){videoPlaying(playerId,kdp,video,'.hero-image')}})})}
var slickSettings={arrows:!1,dots:!0,infinite:!1,slidesToShow:1,slidesToScroll:1}
function slickResize(selector,settings){if($(window).width()>=768){if($(selector).hasClass('slick-initialized')){$(selector).slick('unslick')}
return}
if(!$(selector).hasClass('slick-initialized')){return $(selector).slick(slickSettings)}}
$(document).ready(function(){scrollNav();scaleVideoContainer();initBannerVideoSize(posterImg);scaleBannerVideoSize(posterImg);prepAnimations();mainMenuAnimation();$('.two-block .container > div > div.right').inview({removeClass:!1});if($('svg').length){scrollAnimate()}
if($('[id*="-chart"]').length){$('.chart-view').css('display','block');dataCharts()}
if($('.datacontainer').length){dataContainerClick()}
if(isMobile){if($(window).width()<768){$('.slider').slick(slickSettings)}
$(window).on('resize',slickResize('.slider'))}
$('[tabindex]:not(a)').keypress(function(e){if(e.which==13){$(this).click()}});if($(window).width()<768){slickResize('.chart-display.slider')}
$(window).on('resize',function(){scaleVideoContainer();scaleBannerVideoSize(posterImg);slickResize('.chart-display.slider')})});window.onload=function(){initBannerVideoSize(posterImg);scaleBannerVideoSize(posterImg);if(!isPhone){prepImages()}
if(window.devicePixelRatio>1){prepImages()}
if(!isMobile){if($('.bgimg').length){parallax('.bgimg')}
if($('img + div[id*="Video"]').length){heroVideos()}}}